//
//  ImageFileScanner.swift
//  PhotoAnalyzer
//
//  Created by Thomas Amaranto on 16/06/2026.
//

import Foundation

/// Scans folders for supported image files in a stable order.
final class ImageFileScanner {
    private let fileResourceKeys: Set<URLResourceKey> = [
        .isDirectoryKey,
        .isRegularFileKey,
        .isSymbolicLinkKey
    ]

    /// Creates an image file scanner.
    nonisolated init() {}

    /// Finds supported image files inside a folder.
    /// - Parameters:
    ///   - folderURL: The folder URL to inspect.
    ///   - includeSubfolders: Whether subfolders should be scanned recursively.
    /// - Returns: Supported image file URLs sorted by relative path.
    nonisolated func imageFileURLs(in folderURL: URL, includeSubfolders: Bool = false) -> [URL] {
        if includeSubfolders {
            return recursiveImageFileURLs(in: folderURL)
        }

        return directImageFileURLs(in: folderURL)
    }

    /// Finds supported image files directly inside a folder.
    /// - Parameter folderURL: The folder URL to inspect.
    /// - Returns: Supported image file URLs sorted by file name.
    nonisolated private func directImageFileURLs(in folderURL: URL) -> [URL] {
        let fileURLs = (try? FileManager.default.contentsOfDirectory(
            at: folderURL,
            includingPropertiesForKeys: Array(fileResourceKeys),
            options: [.skipsHiddenFiles]
        )) ?? []

        var supportedFileURLs: [URL] = []
        let sortedFileURLs = fileURLs.sorted {
            $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending
        }

        for fileURL in sortedFileURLs {
            let resourceValues = try? fileURL.resourceValues(forKeys: fileResourceKeys)
            let isRegularFile = resourceValues?.isRegularFile ?? false
            let isSymbolicLink = resourceValues?.isSymbolicLink ?? false

            guard !isSymbolicLink else {
                continue
            }

            guard isRegularFile else {
                continue
            }

            if SupportedImageFormats.contains(fileURL) {
                print("File discovered: \(fileURL.lastPathComponent)")
                supportedFileURLs.append(fileURL)
            } else {
                print("File skipped because unsupported extension: \(fileURL.lastPathComponent)")
            }
        }

        return supportedFileURLs
    }

    /// Finds supported image files recursively, skipping generated package folders and symlinks.
    /// - Parameter folderURL: The folder URL to inspect.
    /// - Returns: Supported image file URLs sorted by path relative to `folderURL`.
    nonisolated private func recursiveImageFileURLs(in folderURL: URL) -> [URL] {
        guard let enumerator = FileManager.default.enumerator(
            at: folderURL,
            includingPropertiesForKeys: Array(fileResourceKeys),
            options: [.skipsHiddenFiles, .skipsPackageDescendants]
        ) else {
            return []
        }

        var supportedFileURLs: [URL] = []

        for case let fileURL as URL in enumerator {
            let resourceValues = try? fileURL.resourceValues(forKeys: fileResourceKeys)
            let isSymbolicLink = resourceValues?.isSymbolicLink ?? false

            guard !isSymbolicLink else {
                continue
            }

            if resourceValues?.isDirectory == true {
                if shouldSkipDirectory(fileURL) {
                    enumerator.skipDescendants()
                }
                continue
            }

            guard resourceValues?.isRegularFile == true else {
                continue
            }

            if SupportedImageFormats.contains(fileURL) {
                print("File discovered: \(relativePath(for: fileURL, relativeTo: folderURL))")
                supportedFileURLs.append(fileURL)
            } else {
                print("File skipped because unsupported extension: \(relativePath(for: fileURL, relativeTo: folderURL))")
            }
        }

        return supportedFileURLs.sorted {
            relativePath(for: $0, relativeTo: folderURL)
                .localizedStandardCompare(relativePath(for: $1, relativeTo: folderURL)) == .orderedAscending
        }
    }

    /// Returns whether a directory should be excluded from recursive scans.
    /// - Parameter url: The directory URL to inspect.
    /// - Returns: `true` when the directory is generated by PhotoAnalyzer.
    nonisolated private func shouldSkipDirectory(_ url: URL) -> Bool {
        let folderName = url.lastPathComponent
        return folderName == AIAnalysisPackagePaths.folderName
            || folderName.contains("_\(AIAnalysisPackagePaths.folderName)_")
    }

    /// Builds a stable display/sort path relative to the selected dataset folder.
    /// - Parameters:
    ///   - url: The discovered file URL.
    ///   - folderURL: The selected dataset folder URL.
    /// - Returns: A path relative to the selected folder when possible.
    nonisolated private func relativePath(for url: URL, relativeTo folderURL: URL) -> String {
        let folderPath = folderURL.standardizedFileURL.path
        let filePath = url.standardizedFileURL.path
        let prefix = folderPath.hasSuffix("/") ? folderPath : "\(folderPath)/"

        guard filePath.hasPrefix(prefix) else {
            return url.lastPathComponent
        }

        return String(filePath.dropFirst(prefix.count))
    }
}
