//
//  ContentView.swift
//  PhotoAnalyzer
//
//  Created by Thomas Amaranto on 15/06/2026.
//

import AppKit
import SwiftUI

/// Main interface for the PhotoAnalyzer macOS application.
struct ContentView: View {
    private enum Layout {
        static let contentSpacing: CGFloat = 16
        static let contentPadding: CGFloat = 26
        static let mainColumnSpacing: CGFloat = 12
        static let dashboardSpacing: CGFloat = 18
        static let windowWidth: CGFloat = 1200
        static let windowDefaultHeight: CGFloat = 800
        static let windowMinimumHeight: CGFloat = 820
        static let contactSheetViewerWidth: CGFloat = 1000
        static let contactSheetViewerHeight: CGFloat = 720
        static let contactSheetViewerMinimumWidth: CGFloat = 760
        static let contactSheetViewerMinimumHeight: CGFloat = 520
    }

    /// The security-scoped folder URL selected by the user.
    @State private var selectedFolderURL: URL?

    /// Optional security-scoped output folder for generated AI packages.
    @State private var selectedOutputFolderURL: URL?

    /// Whether selected dataset subfolders should be scanned.
    @State private var includeSubfolders = false

    /// User-facing state for the selected dataset.
    @State private var datasetState = DatasetUIState.initial

    /// User-facing state for the latest AI package export.
    @State private var packageState = AIPackageUIState.initial

    /// The latest statistics computed from the analyzed photos.
    @State private var statistics: PhotoStatistics?

    /// The contact sheet preview image generated by the latest package export.
    @State private var contactSheetPreviewImage: NSImage?

    /// Dedicated macOS window for inspecting the generated contact sheet.
    @State private var contactSheetViewerWindow: NSWindow?

    /// Whether a folder analysis is currently running.
    @State private var isAnalyzing = false

    /// The current operation phase shown at the bottom of the interface.
    @State private var analysisPhase: AnalysisPhase = .ready

    /// The view hierarchy for the PhotoAnalyzer interface.
    var body: some View {
        VStack(alignment: .leading, spacing: Layout.contentSpacing) {
            AppHeaderView()

            DatasetActionView(
                datasetState: datasetState,
                outputFolderURL: selectedOutputFolderURL,
                isAnalyzing: isAnalyzing,
                includeSubfolders: $includeSubfolders,
                selectFolder: selectFolder,
                selectOutputFolder: selectOutputFolder,
                analyze: analyzeSelectedFolder
            )

            HStack(alignment: .top, spacing: Layout.dashboardSpacing) {
                VStack(spacing: Layout.mainColumnSpacing) {
                    AIPackageCardView(
                        packageState: packageState,
                        isAnalyzing: isAnalyzing,
                        openPackage: openPackage,
                        revealPackage: revealPackage
                    )

                    DatasetOverviewView(statistics: statistics)
                }
                .frame(maxWidth: .infinity, alignment: .top)

                ContactSheetPreviewView(
                    image: contactSheetPreviewImage,
                    packageStatus: packageState.status,
                    openViewer: openContactSheetViewer
                )
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
            }
            .frame(maxHeight: .infinity, alignment: .top)

            Spacer(minLength: 0)

            StatusFooterView(
                statusMessage: analysisPhase.displayText,
                isBusy: isAnalyzing
            )
        }
        .padding(Layout.contentPadding)
        .frame(minWidth: Layout.windowWidth, minHeight: Layout.windowMinimumHeight, alignment: .topLeading)
        .background(
            WindowPlacementView(
                size: CGSize(width: Layout.windowWidth, height: Layout.windowDefaultHeight),
                minimumSize: CGSize(width: Layout.windowWidth, height: Layout.windowMinimumHeight)
            )
            .frame(width: 0, height: 0)
        )
        .onChange(of: includeSubfolders) { _, _ in
            updateSupportedFileCountForSelectedFolder()
        }
    }

    /// Opens a folder picker and stores the selected folder path.
    private func selectFolder() {
        guard !isAnalyzing else {
            return
        }

        let panel = NSOpenPanel()
        panel.canChooseFiles = false
        panel.canChooseDirectories = true
        panel.allowsMultipleSelection = false
        panel.canCreateDirectories = false

        guard panel.runModal() == .OK, let url = panel.url else {
            return
        }

        selectedFolderURL = url
        statistics = nil
        packageState = .initial
        contactSheetPreviewImage = nil

        let supportedFileCount = supportedFileCount(in: url, includeSubfolders: includeSubfolders)
        datasetState = DatasetUIState(
            folderURL: url,
            supportedFileCount: supportedFileCount,
            analyzedPhotoCount: nil,
            analysisStatus: .folderSelected
        )
        analysisPhase = .ready
    }

    /// Opens a folder picker and stores the optional AI package output folder.
    private func selectOutputFolder() {
        guard !isAnalyzing else {
            return
        }

        let panel = NSOpenPanel()
        panel.canChooseFiles = false
        panel.canChooseDirectories = true
        panel.allowsMultipleSelection = false
        panel.canCreateDirectories = true
        panel.prompt = "Select Output Folder"

        guard panel.runModal() == .OK, let url = panel.url else {
            return
        }

        selectedOutputFolderURL = url
        packageState = .initial
        contactSheetPreviewImage = nil
        analysisPhase = .ready
    }

    /// Starts analysis for the selected folder.
    private func analyzeSelectedFolder() {
        guard !isAnalyzing else {
            return
        }

        guard let selectedFolderURL else {
            analysisPhase = .noFolderSelected
            return
        }

        guard (datasetState.supportedFileCount ?? 0) > 0 else {
            analysisPhase = .noSupportedFiles
            return
        }

        Task {
            await analyzeSelectedFolderFiles(in: selectedFolderURL)
        }
    }

    /// Runs folder analysis and package export for the selected folder.
    /// - Parameter folderURL: The folder URL selected by the user.
    private func analyzeSelectedFolderFiles(in folderURL: URL) async {
        guard !isAnalyzing else {
            return
        }

        let outputFolderURL = selectedOutputFolderURL
        let shouldIncludeSubfolders = includeSubfolders
        let packagePaths = AIAnalysisPackagePaths(
            datasetFolderURL: folderURL,
            outputFolderURL: outputFolderURL
        )

        isAnalyzing = true
        defer {
            isAnalyzing = false
        }

        statistics = nil
        contactSheetPreviewImage = nil
        datasetState.analysisStatus = .analyzing
        datasetState.analyzedPhotoCount = nil
        packageState = AIPackageUIState(
            status: .generating,
            packageURL: packagePaths.packageURL,
            metadataExists: false,
            statisticsExists: false,
            contactSheetExists: false,
            indexExists: false,
            errorMessage: nil
        )

        let datasetAccessGranted = folderURL.startAccessingSecurityScopedResource()
        if !datasetAccessGranted {
            print("Warning: security-scoped access was not granted. Continuing anyway.")
        }

        let outputAccessGranted = outputFolderURL?.startAccessingSecurityScopedResource() ?? false
        defer {
            if datasetAccessGranted {
                folderURL.stopAccessingSecurityScopedResource()
            }

            if outputAccessGranted {
                outputFolderURL?.stopAccessingSecurityScopedResource()
            }
        }

        analysisPhase = .scanningFiles
        let fileURLs = await Task.detached(priority: .utility) {
            ImageFileScanner().imageFileURLs(in: folderURL, includeSubfolders: shouldIncludeSubfolders)
        }.value

        guard !fileURLs.isEmpty else {
            datasetState.supportedFileCount = 0
            datasetState.analysisStatus = .folderSelected
            packageState = .initial
            analysisPhase = .noSupportedFiles
            return
        }

        datasetState.supportedFileCount = fileURLs.count

        analysisPhase = .readingMetadata
        let folderAnalysisResult = await Task.detached(priority: .utility) {
            await FolderAnalysisService().analyzeFilesWithExportMetadata(fileURLs)
        }.value

        analysisPhase = .generatingStatistics
        let generatedStatistics = await Task.detached(priority: .utility) {
            PhotoStatisticsService().buildStatistics(from: folderAnalysisResult.photos)
        }.value

        statistics = generatedStatistics
        datasetState.analyzedPhotoCount = folderAnalysisResult.photos.count

        let exporter = AIAnalysisPackageExporter()

        do {
            analysisPhase = .exportingAIPackage
            let paths = try await Task.detached(priority: .utility) {
                try exporter.exportDataFiles(
                    for: folderURL,
                    metadata: folderAnalysisResult.exportMetadata,
                    sourceFileURLs: folderAnalysisResult.fileURLs,
                    statistics: generatedStatistics,
                    paths: packagePaths
                )
            }.value

            analysisPhase = .generatingContactSheet
            try await Task.detached(priority: .utility) {
                try await exporter.exportContactSheet(
                    folderURL: folderURL,
                    sourceFileURLs: folderAnalysisResult.fileURLs,
                    paths: paths
                )
            }.value

            datasetState.analysisStatus = .completed
            packageState = AIPackageUIState(packageURL: paths.packageURL)
            analysisPhase = .completed
            loadContactSheetPreview(from: paths.packageURL)
        } catch {
            let errorDescription = "\(error.localizedDescription) (\(String(reflecting: error)))"
            print("AI package export failed: \(errorDescription)")
            datasetState.analysisStatus = .completedWithExportError
            packageState = AIPackageUIState(packageURL: packagePaths.packageURL, errorMessage: errorDescription)
            analysisPhase = .exportFailed
        }
    }

    /// Counts supported image files in the selected folder.
    /// - Parameters:
    ///   - folderURL: The selected folder URL.
    ///   - includeSubfolders: Whether subfolders should be scanned recursively.
    /// - Returns: Number of supported image files found inside the folder.
    private func supportedFileCount(in folderURL: URL, includeSubfolders: Bool) -> Int {
        let accessGranted = folderURL.startAccessingSecurityScopedResource()
        defer {
            if accessGranted {
                folderURL.stopAccessingSecurityScopedResource()
            }
        }

        return ImageFileScanner().imageFileURLs(in: folderURL, includeSubfolders: includeSubfolders).count
    }

    /// Recounts supported files after scan options change.
    private func updateSupportedFileCountForSelectedFolder() {
        guard !isAnalyzing, let selectedFolderURL else {
            return
        }

        statistics = nil
        packageState = .initial
        contactSheetPreviewImage = nil
        datasetState.supportedFileCount = supportedFileCount(
            in: selectedFolderURL,
            includeSubfolders: includeSubfolders
        )
        datasetState.analyzedPhotoCount = nil
        datasetState.analysisStatus = .folderSelected
        analysisPhase = .ready
    }

    /// Loads the generated contact sheet preview image.
    /// - Parameter packageURL: The package folder URL.
    private func loadContactSheetPreview(from packageURL: URL) {
        let paths = AIAnalysisPackagePaths(packageURL: packageURL)
        contactSheetPreviewImage = NSImage(contentsOf: paths.contactSheetURL)
    }

    /// Opens the generated contact sheet in a dedicated viewer.
    private func openContactSheetViewer() {
        guard let contactSheetPreviewImage else {
            return
        }

        if let contactSheetViewerWindow, contactSheetViewerWindow.isVisible {
            contactSheetViewerWindow.makeKeyAndOrderFront(nil)
            return
        }

        let window = NSWindow(
            contentRect: NSRect(
                x: 0,
                y: 0,
                width: Layout.contactSheetViewerWidth,
                height: Layout.contactSheetViewerHeight
            ),
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )
        window.title = "Contact Sheet"
        window.minSize = NSSize(
            width: Layout.contactSheetViewerMinimumWidth,
            height: Layout.contactSheetViewerMinimumHeight
        )
        window.isReleasedWhenClosed = false
        window.contentViewController = NSHostingController(
            rootView: ContactSheetViewerView(image: contactSheetPreviewImage) { [weak window] in
                window?.close()
            }
        )
        window.center()
        window.makeKeyAndOrderFront(nil)
        contactSheetViewerWindow = window
    }

    /// Opens the generated package folder.
    private func openPackage() {
        guard let packageURL = packageState.packageURL else {
            return
        }

        NSWorkspace.shared.open(packageURL)
    }

    /// Reveals the generated package folder in Finder.
    private func revealPackage() {
        guard let packageURL = packageState.packageURL else {
            return
        }

        NSWorkspace.shared.activateFileViewerSelecting([packageURL])
    }
}

/// Preview provider for the PhotoAnalyzer content view.
#Preview {
    ContentView()
}
