//
//  ContentView.swift
//  PhotoAnalyzer
//
//  Created by Thomas Amaranto on 15/06/2026.
//

import AppKit
import SwiftUI

/// Main interface for the PhotoAnalyzer macOS application.
struct ContentView: View {
    /// The security-scoped folder URL selected by the user.
    @State private var selectedFolderURL: URL?

    /// User-facing state for the selected dataset.
    @State private var datasetState = DatasetUIState.initial

    /// User-facing state for the latest AI package export.
    @State private var packageState = AIPackageUIState.initial

    /// The latest statistics computed from the analyzed photos.
    @State private var statistics: PhotoStatistics?

    /// The contact sheet preview image generated by the latest package export.
    @State private var contactSheetPreviewImage: NSImage?

    /// Dedicated macOS window for inspecting the generated contact sheet.
    @State private var contactSheetViewerWindow: NSWindow?


    /// Whether a folder analysis is currently running.
    @State private var isAnalyzing = false

    /// The current operation phase shown at the bottom of the interface.
    @State private var analysisPhase: AnalysisPhase = .ready

    /// The view hierarchy for the PhotoAnalyzer interface.
    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            AppHeaderView()

            DatasetActionView(
                datasetState: datasetState,
                isAnalyzing: isAnalyzing,
                selectFolder: selectFolder,
                analyze: analyzeSelectedFolder
            )

            HStack(alignment: .top, spacing: 18) {
                VStack(spacing: 12) {
                    AIPackageCardView(
                        packageState: packageState,
                        openPackage: openPackage,
                        revealPackage: revealPackage
                    )

                    DatasetOverviewView(statistics: statistics)
                }
                .frame(maxWidth: .infinity, alignment: .top)

                ContactSheetPreviewView(
                    image: contactSheetPreviewImage,
                    packageStatus: packageState.status,
                    openViewer: openContactSheetViewer
                )
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .top)
            }
            .frame(maxHeight: .infinity, alignment: .top)

            Spacer(minLength: 0)

            StatusFooterView(
                statusMessage: analysisPhase.displayText,
                isBusy: isAnalyzing
            )
        }
        .padding(26)
        .frame(minWidth: 1200, minHeight: 800, alignment: .topLeading)
        .background(
            WindowPlacementView(
                size: CGSize(width: 1200, height: 800),
                minimumSize: CGSize(width: 1200, height: 800)
            )
            .frame(width: 0, height: 0)
        )
    }

    /// Opens a folder picker and stores the selected folder path.
    private func selectFolder() {
        guard !isAnalyzing else {
            return
        }

        let panel = NSOpenPanel()
        panel.canChooseFiles = false
        panel.canChooseDirectories = true
        panel.allowsMultipleSelection = false
        panel.canCreateDirectories = false

        guard panel.runModal() == .OK, let url = panel.url else {
            return
        }

        selectedFolderURL = url
        statistics = nil
        packageState = .initial
        contactSheetPreviewImage = nil

        let supportedFileCount = supportedFileCount(in: url)
        datasetState = DatasetUIState(
            folderURL: url,
            supportedFileCount: supportedFileCount,
            analyzedPhotoCount: nil,
            analysisStatus: .folderSelected
        )
        analysisPhase = .ready
    }

    /// Starts analysis for the selected folder.
    private func analyzeSelectedFolder() {
        guard !isAnalyzing else {
            return
        }

        guard let selectedFolderURL else {
            analysisPhase = .noFolderSelected
            return
        }

        guard (datasetState.supportedFileCount ?? 0) > 0 else {
            analysisPhase = .noSupportedFiles
            return
        }

        Task {
            await analyzeSelectedFolderFiles(in: selectedFolderURL)
        }
    }

    /// Runs folder analysis and package export for the selected folder.
    /// - Parameter folderURL: The folder URL selected by the user.
    private func analyzeSelectedFolderFiles(in folderURL: URL) async {
        guard !isAnalyzing else {
            return
        }

        isAnalyzing = true
        defer {
            isAnalyzing = false
        }

        statistics = nil
        contactSheetPreviewImage = nil
        datasetState.analysisStatus = .analyzing
        datasetState.analyzedPhotoCount = nil
        packageState = AIPackageUIState(
            status: .generating,
            packageURL: AIAnalysisPackagePaths(folderURL: folderURL).packageURL,
            metadataExists: false,
            statisticsExists: false,
            contactSheetExists: false,
            indexExists: false,
            errorMessage: nil
        )

        let accessGranted = folderURL.startAccessingSecurityScopedResource()
        if !accessGranted {
            print("Warning: security-scoped access was not granted. Continuing anyway.")
        }

        defer {
            if accessGranted {
                folderURL.stopAccessingSecurityScopedResource()
            }
        }

        analysisPhase = .scanningFiles
        let fileURLs = await Task.detached(priority: .utility) {
            ImageFileScanner().imageFileURLs(in: folderURL)
        }.value

        guard !fileURLs.isEmpty else {
            datasetState.supportedFileCount = 0
            datasetState.analysisStatus = .folderSelected
            packageState = .initial
            analysisPhase = .noSupportedFiles
            return
        }

        datasetState.supportedFileCount = fileURLs.count

        analysisPhase = .readingMetadata
        let folderAnalysisResult = await Task.detached(priority: .utility) {
            await FolderAnalysisService().analyzeFilesWithExportMetadata(fileURLs)
        }.value

        analysisPhase = .generatingStatistics
        let generatedStatistics = await Task.detached(priority: .utility) {
            PhotoStatisticsService().buildStatistics(from: folderAnalysisResult.photos)
        }.value

        statistics = generatedStatistics
        datasetState.analyzedPhotoCount = folderAnalysisResult.photos.count

        let expectedPackageURL = AIAnalysisPackagePaths(folderURL: folderURL).packageURL
        let exporter = AIAnalysisPackageExporter()

        do {
            analysisPhase = .exportingAIPackage
            let paths = try await Task.detached(priority: .utility) {
                try exporter.exportDataFiles(
                    for: folderURL,
                    metadata: folderAnalysisResult.exportMetadata,
                    sourceFileURLs: folderAnalysisResult.fileURLs,
                    statistics: generatedStatistics
                )
            }.value

            analysisPhase = .generatingContactSheet
            try await Task.detached(priority: .utility) {
                try exporter.exportContactSheet(
                    folderURL: folderURL,
                    sourceFileURLs: folderAnalysisResult.fileURLs,
                    paths: paths
                )
            }.value

            datasetState.analysisStatus = .completed
            packageState = AIPackageUIState(packageURL: paths.packageURL)
            analysisPhase = .completed
            loadContactSheetPreview(from: paths.packageURL)
        } catch {
            let errorDescription = "\(error.localizedDescription) (\(String(reflecting: error)))"
            print("AI package export failed: \(errorDescription)")
            datasetState.analysisStatus = .completedWithExportError
            packageState = AIPackageUIState(packageURL: expectedPackageURL, errorMessage: errorDescription)
            analysisPhase = .exportFailed
        }
    }

    /// Counts supported image files in the selected folder.
    /// - Parameter folderURL: The selected folder URL.
    /// - Returns: Number of supported image files found directly inside the folder.
    private func supportedFileCount(in folderURL: URL) -> Int {
        let accessGranted = folderURL.startAccessingSecurityScopedResource()
        defer {
            if accessGranted {
                folderURL.stopAccessingSecurityScopedResource()
            }
        }

        return ImageFileScanner().imageFileURLs(in: folderURL).count
    }

    /// Loads the generated contact sheet preview image.
    /// - Parameter packageURL: The package folder URL.
    private func loadContactSheetPreview(from packageURL: URL) {
        let paths = AIAnalysisPackagePaths(packageURL: packageURL)
        contactSheetPreviewImage = NSImage(contentsOf: paths.contactSheetURL)
    }

    /// Opens the generated contact sheet in a dedicated viewer.
    private func openContactSheetViewer() {
        guard let contactSheetPreviewImage else {
            return
        }

        if let contactSheetViewerWindow, contactSheetViewerWindow.isVisible {
            contactSheetViewerWindow.makeKeyAndOrderFront(nil)
            return
        }

        let window = NSWindow(
            contentRect: NSRect(x: 0, y: 0, width: 1000, height: 720),
            styleMask: [.titled, .closable, .miniaturizable, .resizable],
            backing: .buffered,
            defer: false
        )
        window.title = "Contact Sheet"
        window.minSize = NSSize(width: 760, height: 520)
        window.isReleasedWhenClosed = false
        window.contentViewController = NSHostingController(
            rootView: ContactSheetViewerView(image: contactSheetPreviewImage) { [weak window] in
                window?.close()
            }
        )
        window.center()
        window.makeKeyAndOrderFront(nil)
        contactSheetViewerWindow = window
    }

    /// Opens the generated package folder.
    private func openPackage() {
        guard let packageURL = packageState.packageURL else {
            return
        }

        NSWorkspace.shared.open(packageURL)
    }

    /// Reveals the generated package folder in Finder.
    private func revealPackage() {
        guard let packageURL = packageState.packageURL else {
            return
        }

        NSWorkspace.shared.activateFileViewerSelecting([packageURL])
    }
}

/// Preview provider for the PhotoAnalyzer content view.
#Preview {
    ContentView()
}
